# Generated by Django 5.1.4 on 2025-01-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_anmar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
